//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.02 at 04:04:01 PM CET 
//


package de.smile.xml.marina.weirs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TWeirType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TWeirType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="BroadCrestedWeir"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CrestLevel"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Constant"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
 *                             &lt;element name="WaterLevelControlled"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="InitalCrestLevel"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="ListofReferenceNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
 *                                       &lt;element name="WaterLevel"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;choice&gt;
 *                                                 &lt;element name="Constant"&gt;
 *                                                   &lt;simpleType&gt;
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                                     &lt;/restriction&gt;
 *                                                   &lt;/simpleType&gt;
 *                                                 &lt;/element&gt;
 *                                                 &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
 *                                               &lt;/choice&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="PControllerFactor" minOccurs="0"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="DControllerFactor" minOccurs="0"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BroadCrestedTopoWeir"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CrestLevel"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Constant"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UnderFlowWeir"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SluiceLevel"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Constant"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UnderFlowTopoWeir"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SluiceLevel"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Constant"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NeedleWeir"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Opening"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Constant"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="TimeSeriesOfOpening" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
 *                             &lt;element name="WaterLevelControlled"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="InitalOpening"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="ListofReferenceNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
 *                                       &lt;element name="WaterLevel"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;choice&gt;
 *                                                 &lt;element name="Constant"&gt;
 *                                                   &lt;simpleType&gt;
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                                     &lt;/restriction&gt;
 *                                                   &lt;/simpleType&gt;
 *                                                 &lt;/element&gt;
 *                                                 &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
 *                                               &lt;/choice&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="PControllerFactor" minOccurs="0"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="DControllerFactor" minOccurs="0"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RadialGate"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="OpeningHight" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TWeirType", propOrder = {
    "broadCrestedWeir",
    "broadCrestedTopoWeir",
    "underFlowWeir",
    "underFlowTopoWeir",
    "needleWeir",
    "radialGate"
})
public class TWeirType {

    @XmlElement(name = "BroadCrestedWeir")
    protected TWeirType.BroadCrestedWeir broadCrestedWeir;
    @XmlElement(name = "BroadCrestedTopoWeir")
    protected TWeirType.BroadCrestedTopoWeir broadCrestedTopoWeir;
    @XmlElement(name = "UnderFlowWeir")
    protected TWeirType.UnderFlowWeir underFlowWeir;
    @XmlElement(name = "UnderFlowTopoWeir")
    protected TWeirType.UnderFlowTopoWeir underFlowTopoWeir;
    @XmlElement(name = "NeedleWeir")
    protected TWeirType.NeedleWeir needleWeir;
    @XmlElement(name = "RadialGate")
    protected TWeirType.RadialGate radialGate;

    /**
     * Gets the value of the broadCrestedWeir property.
     * 
     * @return
     *     possible object is
     *     {@link TWeirType.BroadCrestedWeir }
     *     
     */
    public TWeirType.BroadCrestedWeir getBroadCrestedWeir() {
        return broadCrestedWeir;
    }

    /**
     * Sets the value of the broadCrestedWeir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWeirType.BroadCrestedWeir }
     *     
     */
    public void setBroadCrestedWeir(TWeirType.BroadCrestedWeir value) {
        this.broadCrestedWeir = value;
    }

    /**
     * Gets the value of the broadCrestedTopoWeir property.
     * 
     * @return
     *     possible object is
     *     {@link TWeirType.BroadCrestedTopoWeir }
     *     
     */
    public TWeirType.BroadCrestedTopoWeir getBroadCrestedTopoWeir() {
        return broadCrestedTopoWeir;
    }

    /**
     * Sets the value of the broadCrestedTopoWeir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWeirType.BroadCrestedTopoWeir }
     *     
     */
    public void setBroadCrestedTopoWeir(TWeirType.BroadCrestedTopoWeir value) {
        this.broadCrestedTopoWeir = value;
    }

    /**
     * Gets the value of the underFlowWeir property.
     * 
     * @return
     *     possible object is
     *     {@link TWeirType.UnderFlowWeir }
     *     
     */
    public TWeirType.UnderFlowWeir getUnderFlowWeir() {
        return underFlowWeir;
    }

    /**
     * Sets the value of the underFlowWeir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWeirType.UnderFlowWeir }
     *     
     */
    public void setUnderFlowWeir(TWeirType.UnderFlowWeir value) {
        this.underFlowWeir = value;
    }

    /**
     * Gets the value of the underFlowTopoWeir property.
     * 
     * @return
     *     possible object is
     *     {@link TWeirType.UnderFlowTopoWeir }
     *     
     */
    public TWeirType.UnderFlowTopoWeir getUnderFlowTopoWeir() {
        return underFlowTopoWeir;
    }

    /**
     * Sets the value of the underFlowTopoWeir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWeirType.UnderFlowTopoWeir }
     *     
     */
    public void setUnderFlowTopoWeir(TWeirType.UnderFlowTopoWeir value) {
        this.underFlowTopoWeir = value;
    }

    /**
     * Gets the value of the needleWeir property.
     * 
     * @return
     *     possible object is
     *     {@link TWeirType.NeedleWeir }
     *     
     */
    public TWeirType.NeedleWeir getNeedleWeir() {
        return needleWeir;
    }

    /**
     * Sets the value of the needleWeir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWeirType.NeedleWeir }
     *     
     */
    public void setNeedleWeir(TWeirType.NeedleWeir value) {
        this.needleWeir = value;
    }

    /**
     * Gets the value of the radialGate property.
     * 
     * @return
     *     possible object is
     *     {@link TWeirType.RadialGate }
     *     
     */
    public TWeirType.RadialGate getRadialGate() {
        return radialGate;
    }

    /**
     * Sets the value of the radialGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWeirType.RadialGate }
     *     
     */
    public void setRadialGate(TWeirType.RadialGate value) {
        this.radialGate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CrestLevel"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Constant"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "crestLevel"
    })
    public static class BroadCrestedTopoWeir {

        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "CrestLevel", required = true)
        protected TWeirType.BroadCrestedTopoWeir.CrestLevel crestLevel;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the crestLevel property.
         * 
         * @return
         *     possible object is
         *     {@link TWeirType.BroadCrestedTopoWeir.CrestLevel }
         *     
         */
        public TWeirType.BroadCrestedTopoWeir.CrestLevel getCrestLevel() {
            return crestLevel;
        }

        /**
         * Sets the value of the crestLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link TWeirType.BroadCrestedTopoWeir.CrestLevel }
         *     
         */
        public void setCrestLevel(TWeirType.BroadCrestedTopoWeir.CrestLevel value) {
            this.crestLevel = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Constant"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "constant",
            "timeSeries"
        })
        public static class CrestLevel {

            @XmlElement(name = "Constant")
            protected Double constant;
            @XmlElement(name = "TimeSeries")
            protected TTimeSeries timeSeries;

            /**
             * Gets the value of the constant property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getConstant() {
                return constant;
            }

            /**
             * Sets the value of the constant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setConstant(Double value) {
                this.constant = value;
            }

            /**
             * Gets the value of the timeSeries property.
             * 
             * @return
             *     possible object is
             *     {@link TTimeSeries }
             *     
             */
            public TTimeSeries getTimeSeries() {
                return timeSeries;
            }

            /**
             * Sets the value of the timeSeries property.
             * 
             * @param value
             *     allowed object is
             *     {@link TTimeSeries }
             *     
             */
            public void setTimeSeries(TTimeSeries value) {
                this.timeSeries = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CrestLevel"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Constant"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
     *                   &lt;element name="WaterLevelControlled"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="InitalCrestLevel"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="ListofReferenceNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
     *                             &lt;element name="WaterLevel"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;choice&gt;
     *                                       &lt;element name="Constant"&gt;
     *                                         &lt;simpleType&gt;
     *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                                           &lt;/restriction&gt;
     *                                         &lt;/simpleType&gt;
     *                                       &lt;/element&gt;
     *                                       &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
     *                                     &lt;/choice&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="PControllerFactor" minOccurs="0"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="DControllerFactor" minOccurs="0"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "crestLevel"
    })
    public static class BroadCrestedWeir {

        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "CrestLevel", required = true)
        protected TWeirType.BroadCrestedWeir.CrestLevel crestLevel;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the crestLevel property.
         * 
         * @return
         *     possible object is
         *     {@link TWeirType.BroadCrestedWeir.CrestLevel }
         *     
         */
        public TWeirType.BroadCrestedWeir.CrestLevel getCrestLevel() {
            return crestLevel;
        }

        /**
         * Sets the value of the crestLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link TWeirType.BroadCrestedWeir.CrestLevel }
         *     
         */
        public void setCrestLevel(TWeirType.BroadCrestedWeir.CrestLevel value) {
            this.crestLevel = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Constant"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
         *         &lt;element name="WaterLevelControlled"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="InitalCrestLevel"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="ListofReferenceNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
         *                   &lt;element name="WaterLevel"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;choice&gt;
         *                             &lt;element name="Constant"&gt;
         *                               &lt;simpleType&gt;
         *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *                                 &lt;/restriction&gt;
         *                               &lt;/simpleType&gt;
         *                             &lt;/element&gt;
         *                             &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
         *                           &lt;/choice&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="PControllerFactor" minOccurs="0"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="DControllerFactor" minOccurs="0"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "constant",
            "timeSeries",
            "waterLevelControlled"
        })
        public static class CrestLevel {

            @XmlElement(name = "Constant")
            protected Double constant;
            @XmlElement(name = "TimeSeries")
            protected TTimeSeries timeSeries;
            @XmlElement(name = "WaterLevelControlled")
            protected TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled waterLevelControlled;

            /**
             * Gets the value of the constant property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getConstant() {
                return constant;
            }

            /**
             * Sets the value of the constant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setConstant(Double value) {
                this.constant = value;
            }

            /**
             * Gets the value of the timeSeries property.
             * 
             * @return
             *     possible object is
             *     {@link TTimeSeries }
             *     
             */
            public TTimeSeries getTimeSeries() {
                return timeSeries;
            }

            /**
             * Sets the value of the timeSeries property.
             * 
             * @param value
             *     allowed object is
             *     {@link TTimeSeries }
             *     
             */
            public void setTimeSeries(TTimeSeries value) {
                this.timeSeries = value;
            }

            /**
             * Gets the value of the waterLevelControlled property.
             * 
             * @return
             *     possible object is
             *     {@link TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled }
             *     
             */
            public TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled getWaterLevelControlled() {
                return waterLevelControlled;
            }

            /**
             * Sets the value of the waterLevelControlled property.
             * 
             * @param value
             *     allowed object is
             *     {@link TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled }
             *     
             */
            public void setWaterLevelControlled(TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled value) {
                this.waterLevelControlled = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="InitalCrestLevel"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="ListofReferenceNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
             *         &lt;element name="WaterLevel"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;choice&gt;
             *                   &lt;element name="Constant"&gt;
             *                     &lt;simpleType&gt;
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
             *                       &lt;/restriction&gt;
             *                     &lt;/simpleType&gt;
             *                   &lt;/element&gt;
             *                   &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
             *                 &lt;/choice&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="PControllerFactor" minOccurs="0"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="DControllerFactor" minOccurs="0"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "initalCrestLevel",
                "listofReferenceNodes",
                "waterLevel",
                "pControllerFactor",
                "dControllerFactor"
            })
            public static class WaterLevelControlled {

                @XmlElement(name = "InitalCrestLevel")
                protected double initalCrestLevel;
                @XmlElement(name = "ListofReferenceNodes", required = true)
                protected TListOfNodes listofReferenceNodes;
                @XmlElement(name = "WaterLevel", required = true)
                protected TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled.WaterLevel waterLevel;
                @XmlElement(name = "PControllerFactor")
                protected Double pControllerFactor;
                @XmlElement(name = "DControllerFactor")
                protected Double dControllerFactor;

                /**
                 * Gets the value of the initalCrestLevel property.
                 * 
                 */
                public double getInitalCrestLevel() {
                    return initalCrestLevel;
                }

                /**
                 * Sets the value of the initalCrestLevel property.
                 * 
                 */
                public void setInitalCrestLevel(double value) {
                    this.initalCrestLevel = value;
                }

                /**
                 * Gets the value of the listofReferenceNodes property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TListOfNodes }
                 *     
                 */
                public TListOfNodes getListofReferenceNodes() {
                    return listofReferenceNodes;
                }

                /**
                 * Sets the value of the listofReferenceNodes property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TListOfNodes }
                 *     
                 */
                public void setListofReferenceNodes(TListOfNodes value) {
                    this.listofReferenceNodes = value;
                }

                /**
                 * Gets the value of the waterLevel property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled.WaterLevel }
                 *     
                 */
                public TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled.WaterLevel getWaterLevel() {
                    return waterLevel;
                }

                /**
                 * Sets the value of the waterLevel property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled.WaterLevel }
                 *     
                 */
                public void setWaterLevel(TWeirType.BroadCrestedWeir.CrestLevel.WaterLevelControlled.WaterLevel value) {
                    this.waterLevel = value;
                }

                /**
                 * Gets the value of the pControllerFactor property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getPControllerFactor() {
                    return pControllerFactor;
                }

                /**
                 * Sets the value of the pControllerFactor property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setPControllerFactor(Double value) {
                    this.pControllerFactor = value;
                }

                /**
                 * Gets the value of the dControllerFactor property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getDControllerFactor() {
                    return dControllerFactor;
                }

                /**
                 * Sets the value of the dControllerFactor property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setDControllerFactor(Double value) {
                    this.dControllerFactor = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;choice&gt;
                 *         &lt;element name="Constant"&gt;
                 *           &lt;simpleType&gt;
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
                 *             &lt;/restriction&gt;
                 *           &lt;/simpleType&gt;
                 *         &lt;/element&gt;
                 *         &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
                 *       &lt;/choice&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "constant",
                    "timeSeries"
                })
                public static class WaterLevel {

                    @XmlElement(name = "Constant")
                    protected Double constant;
                    @XmlElement(name = "TimeSeries")
                    protected TTimeSeries timeSeries;

                    /**
                     * Gets the value of the constant property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public Double getConstant() {
                        return constant;
                    }

                    /**
                     * Sets the value of the constant property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setConstant(Double value) {
                        this.constant = value;
                    }

                    /**
                     * Gets the value of the timeSeries property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TTimeSeries }
                     *     
                     */
                    public TTimeSeries getTimeSeries() {
                        return timeSeries;
                    }

                    /**
                     * Sets the value of the timeSeries property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TTimeSeries }
                     *     
                     */
                    public void setTimeSeries(TTimeSeries value) {
                        this.timeSeries = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Opening"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Constant"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="TimeSeriesOfOpening" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
     *                   &lt;element name="WaterLevelControlled"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="InitalOpening"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="ListofReferenceNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
     *                             &lt;element name="WaterLevel"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;choice&gt;
     *                                       &lt;element name="Constant"&gt;
     *                                         &lt;simpleType&gt;
     *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                                           &lt;/restriction&gt;
     *                                         &lt;/simpleType&gt;
     *                                       &lt;/element&gt;
     *                                       &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
     *                                     &lt;/choice&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="PControllerFactor" minOccurs="0"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="DControllerFactor" minOccurs="0"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "opening"
    })
    public static class NeedleWeir {

        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "Opening", required = true)
        protected TWeirType.NeedleWeir.Opening opening;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the opening property.
         * 
         * @return
         *     possible object is
         *     {@link TWeirType.NeedleWeir.Opening }
         *     
         */
        public TWeirType.NeedleWeir.Opening getOpening() {
            return opening;
        }

        /**
         * Sets the value of the opening property.
         * 
         * @param value
         *     allowed object is
         *     {@link TWeirType.NeedleWeir.Opening }
         *     
         */
        public void setOpening(TWeirType.NeedleWeir.Opening value) {
            this.opening = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Constant"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="TimeSeriesOfOpening" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
         *         &lt;element name="WaterLevelControlled"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="InitalOpening"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="ListofReferenceNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
         *                   &lt;element name="WaterLevel"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;choice&gt;
         *                             &lt;element name="Constant"&gt;
         *                               &lt;simpleType&gt;
         *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *                                 &lt;/restriction&gt;
         *                               &lt;/simpleType&gt;
         *                             &lt;/element&gt;
         *                             &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
         *                           &lt;/choice&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="PControllerFactor" minOccurs="0"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="DControllerFactor" minOccurs="0"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "constant",
            "timeSeriesOfOpening",
            "waterLevelControlled"
        })
        public static class Opening {

            @XmlElement(name = "Constant")
            protected Double constant;
            @XmlElement(name = "TimeSeriesOfOpening")
            protected TTimeSeries timeSeriesOfOpening;
            @XmlElement(name = "WaterLevelControlled")
            protected TWeirType.NeedleWeir.Opening.WaterLevelControlled waterLevelControlled;

            /**
             * Gets the value of the constant property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getConstant() {
                return constant;
            }

            /**
             * Sets the value of the constant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setConstant(Double value) {
                this.constant = value;
            }

            /**
             * Gets the value of the timeSeriesOfOpening property.
             * 
             * @return
             *     possible object is
             *     {@link TTimeSeries }
             *     
             */
            public TTimeSeries getTimeSeriesOfOpening() {
                return timeSeriesOfOpening;
            }

            /**
             * Sets the value of the timeSeriesOfOpening property.
             * 
             * @param value
             *     allowed object is
             *     {@link TTimeSeries }
             *     
             */
            public void setTimeSeriesOfOpening(TTimeSeries value) {
                this.timeSeriesOfOpening = value;
            }

            /**
             * Gets the value of the waterLevelControlled property.
             * 
             * @return
             *     possible object is
             *     {@link TWeirType.NeedleWeir.Opening.WaterLevelControlled }
             *     
             */
            public TWeirType.NeedleWeir.Opening.WaterLevelControlled getWaterLevelControlled() {
                return waterLevelControlled;
            }

            /**
             * Sets the value of the waterLevelControlled property.
             * 
             * @param value
             *     allowed object is
             *     {@link TWeirType.NeedleWeir.Opening.WaterLevelControlled }
             *     
             */
            public void setWaterLevelControlled(TWeirType.NeedleWeir.Opening.WaterLevelControlled value) {
                this.waterLevelControlled = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="InitalOpening"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="ListofReferenceNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
             *         &lt;element name="WaterLevel"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;choice&gt;
             *                   &lt;element name="Constant"&gt;
             *                     &lt;simpleType&gt;
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
             *                       &lt;/restriction&gt;
             *                     &lt;/simpleType&gt;
             *                   &lt;/element&gt;
             *                   &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
             *                 &lt;/choice&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="PControllerFactor" minOccurs="0"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="DControllerFactor" minOccurs="0"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "initalOpening",
                "listofReferenceNodes",
                "waterLevel",
                "pControllerFactor",
                "dControllerFactor"
            })
            public static class WaterLevelControlled {

                @XmlElement(name = "InitalOpening")
                protected double initalOpening;
                @XmlElement(name = "ListofReferenceNodes", required = true)
                protected TListOfNodes listofReferenceNodes;
                @XmlElement(name = "WaterLevel", required = true)
                protected TWeirType.NeedleWeir.Opening.WaterLevelControlled.WaterLevel waterLevel;
                @XmlElement(name = "PControllerFactor")
                protected Double pControllerFactor;
                @XmlElement(name = "DControllerFactor")
                protected Double dControllerFactor;

                /**
                 * Gets the value of the initalOpening property.
                 * 
                 */
                public double getInitalOpening() {
                    return initalOpening;
                }

                /**
                 * Sets the value of the initalOpening property.
                 * 
                 */
                public void setInitalOpening(double value) {
                    this.initalOpening = value;
                }

                /**
                 * Gets the value of the listofReferenceNodes property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TListOfNodes }
                 *     
                 */
                public TListOfNodes getListofReferenceNodes() {
                    return listofReferenceNodes;
                }

                /**
                 * Sets the value of the listofReferenceNodes property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TListOfNodes }
                 *     
                 */
                public void setListofReferenceNodes(TListOfNodes value) {
                    this.listofReferenceNodes = value;
                }

                /**
                 * Gets the value of the waterLevel property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TWeirType.NeedleWeir.Opening.WaterLevelControlled.WaterLevel }
                 *     
                 */
                public TWeirType.NeedleWeir.Opening.WaterLevelControlled.WaterLevel getWaterLevel() {
                    return waterLevel;
                }

                /**
                 * Sets the value of the waterLevel property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TWeirType.NeedleWeir.Opening.WaterLevelControlled.WaterLevel }
                 *     
                 */
                public void setWaterLevel(TWeirType.NeedleWeir.Opening.WaterLevelControlled.WaterLevel value) {
                    this.waterLevel = value;
                }

                /**
                 * Gets the value of the pControllerFactor property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getPControllerFactor() {
                    return pControllerFactor;
                }

                /**
                 * Sets the value of the pControllerFactor property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setPControllerFactor(Double value) {
                    this.pControllerFactor = value;
                }

                /**
                 * Gets the value of the dControllerFactor property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getDControllerFactor() {
                    return dControllerFactor;
                }

                /**
                 * Sets the value of the dControllerFactor property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setDControllerFactor(Double value) {
                    this.dControllerFactor = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;choice&gt;
                 *         &lt;element name="Constant"&gt;
                 *           &lt;simpleType&gt;
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
                 *             &lt;/restriction&gt;
                 *           &lt;/simpleType&gt;
                 *         &lt;/element&gt;
                 *         &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
                 *       &lt;/choice&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "constant",
                    "timeSeries"
                })
                public static class WaterLevel {

                    @XmlElement(name = "Constant")
                    protected Double constant;
                    @XmlElement(name = "TimeSeries")
                    protected TTimeSeries timeSeries;

                    /**
                     * Gets the value of the constant property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public Double getConstant() {
                        return constant;
                    }

                    /**
                     * Sets the value of the constant property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setConstant(Double value) {
                        this.constant = value;
                    }

                    /**
                     * Gets the value of the timeSeries property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TTimeSeries }
                     *     
                     */
                    public TTimeSeries getTimeSeries() {
                        return timeSeries;
                    }

                    /**
                     * Sets the value of the timeSeries property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TTimeSeries }
                     *     
                     */
                    public void setTimeSeries(TTimeSeries value) {
                        this.timeSeries = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="OpeningHight" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "openingHight"
    })
    public static class RadialGate {

        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "OpeningHight")
        protected double openingHight;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the openingHight property.
         * 
         */
        public double getOpeningHight() {
            return openingHight;
        }

        /**
         * Sets the value of the openingHight property.
         * 
         */
        public void setOpeningHight(double value) {
            this.openingHight = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SluiceLevel"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Constant"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "sluiceLevel"
    })
    public static class UnderFlowTopoWeir {

        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "SluiceLevel", required = true)
        protected TWeirType.UnderFlowTopoWeir.SluiceLevel sluiceLevel;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the sluiceLevel property.
         * 
         * @return
         *     possible object is
         *     {@link TWeirType.UnderFlowTopoWeir.SluiceLevel }
         *     
         */
        public TWeirType.UnderFlowTopoWeir.SluiceLevel getSluiceLevel() {
            return sluiceLevel;
        }

        /**
         * Sets the value of the sluiceLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link TWeirType.UnderFlowTopoWeir.SluiceLevel }
         *     
         */
        public void setSluiceLevel(TWeirType.UnderFlowTopoWeir.SluiceLevel value) {
            this.sluiceLevel = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Constant"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "constant",
            "timeSeries"
        })
        public static class SluiceLevel {

            @XmlElement(name = "Constant")
            protected Double constant;
            @XmlElement(name = "TimeSeries")
            protected TTimeSeries timeSeries;

            /**
             * Gets the value of the constant property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getConstant() {
                return constant;
            }

            /**
             * Sets the value of the constant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setConstant(Double value) {
                this.constant = value;
            }

            /**
             * Gets the value of the timeSeries property.
             * 
             * @return
             *     possible object is
             *     {@link TTimeSeries }
             *     
             */
            public TTimeSeries getTimeSeries() {
                return timeSeries;
            }

            /**
             * Sets the value of the timeSeries property.
             * 
             * @param value
             *     allowed object is
             *     {@link TTimeSeries }
             *     
             */
            public void setTimeSeries(TTimeSeries value) {
                this.timeSeries = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SluiceLevel"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Constant"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "sluiceLevel"
    })
    public static class UnderFlowWeir {

        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "SluiceLevel", required = true)
        protected TWeirType.UnderFlowWeir.SluiceLevel sluiceLevel;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the sluiceLevel property.
         * 
         * @return
         *     possible object is
         *     {@link TWeirType.UnderFlowWeir.SluiceLevel }
         *     
         */
        public TWeirType.UnderFlowWeir.SluiceLevel getSluiceLevel() {
            return sluiceLevel;
        }

        /**
         * Sets the value of the sluiceLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link TWeirType.UnderFlowWeir.SluiceLevel }
         *     
         */
        public void setSluiceLevel(TWeirType.UnderFlowWeir.SluiceLevel value) {
            this.sluiceLevel = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Constant"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double"&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="TimeSeries" type="{http://www.example.org/Weirs}TTimeSeries"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "constant",
            "timeSeries"
        })
        public static class SluiceLevel {

            @XmlElement(name = "Constant")
            protected Double constant;
            @XmlElement(name = "TimeSeries")
            protected TTimeSeries timeSeries;

            /**
             * Gets the value of the constant property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getConstant() {
                return constant;
            }

            /**
             * Sets the value of the constant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setConstant(Double value) {
                this.constant = value;
            }

            /**
             * Gets the value of the timeSeries property.
             * 
             * @return
             *     possible object is
             *     {@link TTimeSeries }
             *     
             */
            public TTimeSeries getTimeSeries() {
                return timeSeries;
            }

            /**
             * Sets the value of the timeSeries property.
             * 
             * @param value
             *     allowed object is
             *     {@link TTimeSeries }
             *     
             */
            public void setTimeSeries(TTimeSeries value) {
                this.timeSeries = value;
            }

        }

    }

}
