//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.02 at 04:04:01 PM CET 
//


package de.smile.xml.marina.weirs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TWeir complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TWeir"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ListofNodes" type="{http://www.example.org/Weirs}TListOfNodes"/&gt;
 *         &lt;element name="WeirType" type="{http://www.example.org/Weirs}TWeirType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TWeir", propOrder = {
    "listofNodes",
    "weirType"
})
public class TWeir {

    @XmlElement(name = "ListofNodes", required = true)
    protected TListOfNodes listofNodes;
    @XmlElement(name = "WeirType", required = true)
    protected TWeirType weirType;

    /**
     * Gets the value of the listofNodes property.
     * 
     * @return
     *     possible object is
     *     {@link TListOfNodes }
     *     
     */
    public TListOfNodes getListofNodes() {
        return listofNodes;
    }

    /**
     * Sets the value of the listofNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TListOfNodes }
     *     
     */
    public void setListofNodes(TListOfNodes value) {
        this.listofNodes = value;
    }

    /**
     * Gets the value of the weirType property.
     * 
     * @return
     *     possible object is
     *     {@link TWeirType }
     *     
     */
    public TWeirType getWeirType() {
        return weirType;
    }

    /**
     * Sets the value of the weirType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWeirType }
     *     
     */
    public void setWeirType(TWeirType value) {
        this.weirType = value;
    }

}
