//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.02 at 04:04:00 PM CET 
//


package de.smile.xml.marina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TResultFileType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TResultFileType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TicadSysErg"/&gt;
 *     &lt;enumeration value="Current3DErg"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TResultFileType")
@XmlEnum
public enum TResultFileType {

    @XmlEnumValue("TicadSysErg")
    TICAD_SYS_ERG("TicadSysErg"),
    @XmlEnumValue("Current3DErg")
    CURRENT_3_D_ERG("Current3DErg");
    private final String value;

    TResultFileType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TResultFileType fromValue(String v) {
        for (TResultFileType c: TResultFileType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
