//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.02 at 04:04:00 PM CET 
//


package de.smile.xml.marina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TSoilModelFileType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TSoilModelFileType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CSV"/&gt;
 *     &lt;enumeration value="AVSUCD"/&gt;
 *     &lt;enumeration value="SediMorph"/&gt;
 *     &lt;enumeration value="Delft3D.FM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TSoilModelFileType")
@XmlEnum
public enum TSoilModelFileType {

    CSV("CSV"),
    AVSUCD("AVSUCD"),
    @XmlEnumValue("SediMorph")
    SEDI_MORPH("SediMorph"),
    @XmlEnumValue("Delft3D.FM")
    DELFT_3_D_FM("Delft3D.FM");
    private final String value;

    TSoilModelFileType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TSoilModelFileType fromValue(String v) {
        for (TSoilModelFileType c: TSoilModelFileType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
